// src/mockData.ts
// Datos ficticios basados en la estructura real de la base de datos de Latitud VCP

import type { VentaTour, VentaServicioProveedor } from './types';

// Helper para obtener fecha relativa al día de hoy
const relDate = (offset: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().split('T')[0];
};

export const MOCK_TOURS: VentaTour[] = [
  // HOY ─────────────────────────────────────
  {
    id_venta: 1001,
    n_linea: 1,
    fecha_servicio: relDate(0),
    hora_inicio: '06:30',
    observacion: 'VALLE VIP CONEXIÓN MACHU PICCHU',
    cantidad: 3,
    es_endoso: false,
    nombre_cliente: 'Familia Rodríguez - ARG',
    estado_venta: 'EN_VIAJE',
    id_agencia_aliada: null,
  },
  {
    id_venta: 1002,
    n_linea: 1,
    fecha_servicio: relDate(0),
    hora_inicio: '09:00',
    observacion: 'CITY TOUR CUSCO + QORICANCHA',
    cantidad: 2,
    es_endoso: false,
    nombre_cliente: 'Pareja Martínez - MEX',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: null,
  },
  {
    id_venta: 1003,
    n_linea: 1,
    fecha_servicio: relDate(0),
    hora_inicio: '05:00',
    observacion: 'VISITA A MACHU PICCHU',
    cantidad: 5,
    es_endoso: true,
    nombre_cliente: 'Grupo Kuna Travel',
    estado_venta: 'EN_VIAJE',
    id_agencia_aliada: 3, // Kuna Travel México
  },
  {
    id_venta: 1004,
    n_linea: 1,
    fecha_servicio: relDate(0),
    hora_inicio: '14:00',
    observacion: 'MONTAÑA DE 7 COLORES (RAINBOW MOUNTAIN)',
    cantidad: 4,
    es_endoso: false,
    nombre_cliente: 'Grupo Soave - BRA',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: null,
  },

  // MAÑANA ───────────────────────────────────
  {
    id_venta: 1005,
    n_linea: 1,
    fecha_servicio: relDate(1),
    hora_inicio: '05:00',
    observacion: 'VISITA A MACHU PICCHU',
    cantidad: 2,
    es_endoso: false,
    nombre_cliente: 'Carlos Benítez - BOL',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: null,
  },
  {
    id_venta: 1006,
    n_linea: 1,
    fecha_servicio: relDate(1),
    hora_inicio: '08:00',
    observacion: 'PALLAY PUNCHU - LAGUNA HUMANTAY',
    cantidad: 6,
    es_endoso: true,
    nombre_cliente: 'Grupo Guru Destinos - ARG',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: 4, // Guru Destinos
  },

  // PASADO MAÑANA ────────────────────────────
  {
    id_venta: 1007,
    n_linea: 1,
    fecha_servicio: relDate(2),
    hora_inicio: '06:00',
    observacion: 'VALLE SAGRADO CLÁSICO',
    cantidad: 3,
    es_endoso: false,
    nombre_cliente: 'Ana Lucía Torres - PER',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: null,
  },
  {
    id_venta: 1008,
    n_linea: 1,
    fecha_servicio: relDate(2),
    hora_inicio: '09:00',
    observacion: 'CITY TOUR CUSCO',
    cantidad: 1,
    es_endoso: false,
    nombre_cliente: 'James Williams - USA',
    estado_venta: 'CONFIRMADO',
    id_agencia_aliada: null,
  },
];

export const MOCK_SERVICES: Record<string, VentaServicioProveedor[]> = {
  // Familia Rodríguez - Valle VIP
  '1001-1': [
    {
      id: 2001,
      id_venta: 1001,
      n_linea: 1,
      tipo_servicio: 'TRANSPORTE',
      costo_unitario: 35,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: 'Roberto Quispe',
      terminado: true,
      contratado: true,
      fecha_confirmacion: relDate(0),
      fecha_contratacion: relDate(-1),
      metodo_pago: 'TRANSFERENCIA',
      observaciones_pago: 'Pago BCP Op# 99482',
      observaciones_contables: 'Facturado F001-204',
      observacion: 'Van Hyundai H1 H1Z-892',
      tipo_cambio: 3.75,
      proveedor: { nombre_comercial: 'TRANSTUR CUSCO' },
    },
    {
      id: 2002,
      id_venta: 1001,
      n_linea: 1,
      tipo_servicio: 'GUIA',
      costo_unitario: 80,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: 'Roberto Quispe',
      terminado: true,
      contratado: false,
      metodo_pago: 'YAPE',
      observaciones_pago: 'Pendiente de comprobante',
      tipo_cambio: 3.75,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
    {
      id: 2003,
      id_venta: 1001,
      n_linea: 1,
      tipo_servicio: 'TREN',
      costo_unitario: 52,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: '',
      terminado: true,
      contratado: true,
      fecha_confirmacion: relDate(-1),
      fecha_contratacion: relDate(-2),
      proveedor: { nombre_comercial: 'PERU RAIL' },
    },
    {
      id: 2004,
      id_venta: 1001,
      n_linea: 1,
      tipo_servicio: 'ALMUERZO',
      costo_unitario: 28,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: '',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'RESTAURANT EL FOGÓN URUBAMBA' },
    },
  ],

  // Pareja Martínez - City Tour
  '1002-1': [
    {
      id: 2010,
      id_venta: 1002,
      n_linea: 1,
      tipo_servicio: 'TRANSPORTE',
      costo_unitario: 20,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: 'María Ccoa',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'TRANSTUR CUSCO' },
    },
    {
      id: 2011,
      id_venta: 1002,
      n_linea: 1,
      tipo_servicio: 'GUIA',
      costo_unitario: 60,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: 'María Ccoa',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
    {
      id: 2012,
      id_venta: 1002,
      n_linea: 1,
      tipo_servicio: 'ENTRADA QORICANCHA',
      costo_unitario: 15,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: '',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'MINISTERIO DE CULTURA CUSCO' },
    },
  ],

  // Grupo Kuna Travel - Machu Picchu (endoso)
  '1003-1': [
    {
      id: 2020,
      id_venta: 1003,
      n_linea: 1,
      tipo_servicio: 'ENDOSE',
      costo_unitario: 120,
      moneda: 'USD',
      cantidad_pax: 5,
      nombre_guia: 'Agencia Local MP',
      terminado: true,
      contratado: true,
      fecha_confirmacion: relDate(-1),
      fecha_contratacion: relDate(-3),
      proveedor: { nombre_comercial: 'CONSETTUR MACHUPICCHU' },
    },
    {
      id: 2021,
      id_venta: 1003,
      n_linea: 1,
      tipo_servicio: 'TREN',
      costo_unitario: 52,
      moneda: 'USD',
      cantidad_pax: 5,
      nombre_guia: '',
      terminado: true,
      contratado: true,
      fecha_confirmacion: relDate(-2),
      fecha_contratacion: relDate(-4),
      proveedor: { nombre_comercial: 'INCA RAIL' },
    },
  ],

  // Grupo Soave - Rainbow Mountain
  '1004-1': [
    {
      id: 2030,
      id_venta: 1004,
      n_linea: 1,
      tipo_servicio: 'TRANSPORTE',
      costo_unitario: 25,
      moneda: 'USD',
      cantidad_pax: 4,
      nombre_guia: 'Jhon Ccallo',
      terminado: true,
      contratado: false,
      fecha_confirmacion: relDate(0),
      proveedor: { nombre_comercial: 'TRANSTUR CUSCO' },
    },
    {
      id: 2031,
      id_venta: 1004,
      n_linea: 1,
      tipo_servicio: 'GUIA',
      costo_unitario: 70,
      moneda: 'USD',
      cantidad_pax: 4,
      nombre_guia: 'Jhon Ccallo',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
    {
      id: 2032,
      id_venta: 1004,
      n_linea: 1,
      tipo_servicio: 'CABALLOS',
      costo_unitario: 30,
      moneda: 'PEN',
      cantidad_pax: 4,
      nombre_guia: '',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'COMUNIDAD RACCHI' },
    },
  ],

  // Carlos Benítez - Machu Picchu (mañana)
  '1005-1': [
    {
      id: 2040,
      id_venta: 1005,
      n_linea: 1,
      tipo_servicio: 'TREN',
      costo_unitario: 52,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: '',
      terminado: false,
      contratado: true,
      fecha_contratacion: relDate(0),
      proveedor: { nombre_comercial: 'PERU RAIL' },
    },
    {
      id: 2041,
      id_venta: 1005,
      n_linea: 1,
      tipo_servicio: 'BUS SUBIDA/BAJADA',
      costo_unitario: 12,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: '',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'CONSETTUR MACHUPICCHU' },
    },
    {
      id: 2042,
      id_venta: 1005,
      n_linea: 1,
      tipo_servicio: 'GUIA',
      costo_unitario: 80,
      moneda: 'USD',
      cantidad_pax: 2,
      nombre_guia: 'Luis Mamani',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
  ],

  // Guru Destinos - Humantay (mañana, endoso)
  '1006-1': [
    {
      id: 2050,
      id_venta: 1006,
      n_linea: 1,
      tipo_servicio: 'ENDOSE',
      costo_unitario: 55,
      moneda: 'USD',
      cantidad_pax: 6,
      nombre_guia: 'Operador Local Mollepata',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'OPERADOR HUMANTAY LOCAL' },
    },
  ],

  // Ana Lucía Torres - Valle Sagrado
  '1007-1': [
    {
      id: 2060,
      id_venta: 1007,
      n_linea: 1,
      tipo_servicio: 'TRANSPORTE',
      costo_unitario: 30,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: 'Yolanda Huanca',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'TRANSTUR CUSCO' },
    },
    {
      id: 2061,
      id_venta: 1007,
      n_linea: 1,
      tipo_servicio: 'GUIA',
      costo_unitario: 75,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: 'Yolanda Huanca',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
    {
      id: 2062,
      id_venta: 1007,
      n_linea: 1,
      tipo_servicio: 'ALMUERZO',
      costo_unitario: 20,
      moneda: 'USD',
      cantidad_pax: 3,
      nombre_guia: '',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'RESTAURANT URUBAMBA BUFFET' },
    },
  ],

  // James Williams - City Tour
  '1008-1': [
    {
      id: 2070,
      id_venta: 1008,
      n_linea: 1,
      tipo_servicio: 'TRANSPORTE',
      costo_unitario: 20,
      moneda: 'USD',
      cantidad_pax: 1,
      nombre_guia: 'Pedro Sumiri',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'TRANSTUR CUSCO' },
    },
    {
      id: 2071,
      id_venta: 1008,
      n_linea: 1,
      tipo_servicio: 'GUIA EN INGLÉS',
      costo_unitario: 80,
      moneda: 'USD',
      cantidad_pax: 1,
      nombre_guia: 'Pedro Sumiri',
      terminado: false,
      contratado: false,
      proveedor: { nombre_comercial: 'GUÍAS CUSCO LICENCIADOS' },
    },
  ],
};
